const test = require("node:test");
const assert = require("node:assert/strict");
const zlib = require("node:zlib");

const reports = require("./reports");
const pool = require("../db");

test.after(async () => {
  await pool.end();
});

function extractPdfText(pdf) {
  const source = pdf.toString("latin1");
  const textChunks = [source];
  let streamStart = 0;

  while (true) {
    const marker = source.indexOf("stream", streamStart);
    if (marker === -1) break;

    let dataStart = marker + "stream".length;
    if (source[dataStart] === "\r") dataStart += 1;
    if (source[dataStart] === "\n") dataStart += 1;
    const dataEnd = source.indexOf("endstream", dataStart);
    if (dataEnd === -1) break;

    try {
      const stream = zlib
        .inflateSync(pdf.subarray(dataStart, dataEnd))
        .toString("latin1");
      textChunks.push(stream);
      textChunks.push(
        [...stream.matchAll(/<([0-9a-fA-F]+)>/g)]
          .map((match) => Buffer.from(match[1], "hex").toString("latin1"))
          .join(""),
      );
    } catch {}
    streamStart = dataEnd + "endstream".length;
  }

  return textChunks.join("\n");
}

test("official export list excludes the trend section", () => {
  assert.ok(Array.isArray(reports.REPORT_EXPORT_SECTIONS));
  assert.ok(!reports.REPORT_EXPORT_SECTIONS.includes("ticket_volume_trend"));
  assert.deepEqual(
    reports.normalizeExportSections(),
    reports.REPORT_EXPORT_SECTIONS,
  );
});

test("trend section is rejected as an invalid export option", () => {
  assert.throws(
    () => reports.normalizeExportSections(["ticket_volume_trend"]),
    /Unknown export sections: ticket_volume_trend/,
  );
});

test("ticket-record PDF export includes all records across pages", async () => {
  const tickets = Array.from({ length: 30 }, (_, index) => ({
    ticket_no: `TKT-AUG-2026-${String(index + 1).padStart(3, "0")}`,
    motorist_name: `Test Motorist ${index + 1}`,
    violation_type: "Parking Violation",
    status: "pending",
    balance_due: 500,
  }));
  const pdf = await reports.generateReportPdf(
    {
      meta: { label: "August 2026", generated_by: "Test Admin" },
      tickets,
    },
    {
      period: "monthly",
      year: 2026,
      month: 8,
      sections: ["ticket_records"],
    },
  );

  const pdfSource = pdf.toString("latin1");
  const pdfText = extractPdfText(pdf);
  const pageCount = (pdfSource.match(/\/Type\s*\/Page\b/g) || []).length;

  assert.equal(pageCount, 3, "expected the cover and two ticket-record pages");
  for (const ticket of tickets) {
    assert.ok(
      pdfText.includes(ticket.ticket_no),
      `missing ${ticket.ticket_no}`,
    );
  }
  assert.match(pdfText, /Report scope: August 2026/);
  assert.match(
    pdfText,
    /Official report generated by the SJTMO reporting system\./,
  );
});
